# action.yml
name: 'custodian'
description: 'Runs custodian policies'
inputs:
  policy-to-run:  # id of input
    description: 'Policy to run'
    required: true
    default: 's3-encrypt-bucket.yml'
outputs:
  run-log: # id of output
    description: 'Run logs'
runs:
  using: 'docker'
  image: 'cloud-custodian/Dockerfile'
  args:
    - ${{ inputs.policy-to-run }}
