on:
  release:
    types: [created]

name: Test Custodian Mailer

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      uses: docker://cloud-custodian/cloud-custodian/mailer

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run Policy
      run: |
        "c7n-mailer -c templates/mailer.yml --run && custodian run --output-dir=.  --verbose --cache-period=0 --profile ${params.AWS_PROFILE} --region ${params.AWS_REGION}"
