# This is a basic workflow to help you get started with Actions

name: Custodian Mailer Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: 'cloud-custodian/cloud-custodian.git'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create output directory
      run: mkdir output
 
    - name: Install venv
      run: sudo apt-get install python3-venv
    
    - name: Install custodian
      run: python3 -m venv custodian
    
    - name: Install c7n
      run: pip install c7n
    
    - name: See working directory
      run: ls -la
    
    - name: See contents of custodian
      run: ls -la ./custodian

    - name: See contents of custodian
      run: ls -la ./custodian/bin
      
    - name: Activate custodian
      run: |
        sh '. custodian/bin/activate ; ' +
        custodian schema ec2.actions
    
      
