# This is a basic workflow to help you get started with Actions

name: Custodian Mailer Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  watch:
    types: [started] 
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-custodian-policy:
    runs-on: ubuntu-latest
    name: Runs a custodian job
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Run a specific policy
        uses: ././policies # Uses an action in the root directory
        id: policy
        with:
          policy-to-run: 's3-encrypt-bucket.yml'
          
      # Use the output from the `hello` step
      - name: Get the run logs
        run: echo "Policy results - ${{ steps.policy.outputs.run-log }}"  
      
