trigger:
- master

jobs:
  yaml-schema-validation: 
    - job: 'Validate'
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
        - checkout: self
        - task: UsePythonVersion@0
          displayName: "Set Python Version"
          inputs:
            versionSpec: '3.8'
            architecture: 'x64'
        - script: pip install --upgrade pip
          displayName: Upgrade pip
        - script: pip install c7n
          displayName: Install custodian
        - script: custodian validate vpc-test-policy.yaml
          displayName: Validate vpc policy file
