on:
  watch:
    types: [started]
    
jobs:
  custodian-policy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
#     - name: Create logs directory
#       with:
#         args: "mkdir logs"
    - name: Check custodian schema
      uses: docker://cloudcustodian/c7n
      with:
        args: "run -s ./logs ./policies/s3-bucket-encryption-disabled.yml --region us-east-1"
