on:
  schedule:
  - cron: "0 12 * * *"
    
jobs:
  custodian-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Run custodian command
      uses: docker://cloudcustodian/c7n
      with: 
        args: "run --output-dir s3://landon-custodian-logs policies/s3-bucket-encryption-disabled.yml --verbose"
