on:
  watch:
    types: [started]
    
jobs:
  custodian-policy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check custodian schema	    
      uses: docker://cloudcustodiancustodian/c7n:latest
      with:
        args: "custodian schema ec2.actions"
