name: testing file uploads

on:
  watch:
    types: [started] 

# on:
#  push:
#   branches:
#     - master

jobs:
  s3-update:
    runs-on: ubuntu-latest
    steps:
    
    - name: configure aws credentials
      uses: tpaschalis/s3-cp-action@v0.2.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-duration-seconds: 1200
  
