name: testing file uploads

on:
  watch:
    types: [started] 

# on:
#  push:
#   branches:
#     - master

jobs:
  s3-update:
    runs-on: ubuntu-latest
    steps:
    
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-duration-seconds: 1200
          
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1.2.0
    
    - name: Upload files to S3
      run: |
          #!/bin/bash
           set -ex
           ls -ltra
           aws s3 sync ./templates/ s3://cpbucket-ldale/ --exclude "*" --include "*.yml"
           for region in "${all_regions[@]}"
           done  
