name: copy to multiple buckets 

on:
  watch:
    types: [started] 

jobs:
  s3-update:
    runs-on: ubuntu-latest
    steps:   
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - uses: actions/checkout@v2 
      
    - name: Upload files to S3
      working-directory: $GITHUB_WORKSPACE
      run: |
        #!/usr/bin/env bash
          regions=(us-east-1 us-west-2)
          for region in "${regions[@]}"
          do
            echo "${region}"          
            bucket="cpbucket-ldale-${region}"
            aws s3 sync $GITHUB_WORKSPACE/templates/ s3://$bucket/templates/  --exclude "*" --include "*.yml"
          done  
