name: testing file uploads

on:
  watch:
    types: [started] 

# on:
#  push:
#   branches:
#     - master

jobs:
  s3-update:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: cpbucket-ldale
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS-REGION: us-east-1
